AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-durable-lambda-experiments

  Sample SAM Template for aws-durable-lambda-experiments
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: 00-hello-world/
      Handler: handler.lambdaHandler
      Runtime: nodejs24.x
      Timeout: 900
      Architectures:
        - x86_64
      AutoPublishAlias: Live
      DurableConfig:
        ExecutionTimeout: 900
        RetentionPeriodInDays: 7
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        Format: cjs
        EntryPoints:
          - src/handler.ts

Outputs:
  HelloWorldFunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt HelloWorldFunctionUrl.FunctionUrl
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
